name: CI-Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, feedback ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests with Gradle
        run: ./gradlew clean test jacocoTestReport

      - name: Test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-test-report
          path: build/reports/tests/test

      - name: Jacoco reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-test-report
          path: build/reports/jacoco/test