name: CI-Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, feedback ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests with Gradle
        run: ./gradlew clean test jacocoTestReport

      - name: Test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-test-report
          path: build/reports/tests/test

      - name: Jacoco reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-test-report
          path: build/reports/jacoco/test

      - name: SpotLess reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-test-report
          path: build/reports/spotbugs

      - name: Allure reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/allure-results

      - name: Generate Allure report
        if: always()
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.33.0/allure-2.33.0.tgz
          tar -xvzf allure-2.33.0.tgz
          ./allure-2.33.0/bin/allure generate build/allure-results --clean -o build/allure-report

      - name: Publish Allure reports
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/allure-report
          publish_branch: gh-pages
          keep_files: true